---
- name: Provisioning webservers group
  hosts: webservers
  gather_facts: false
  vars:
    security_autoupdate_reboot: "true"
    security_autoupdate_reboot_time: "03:00"
    swap_file_size_mb: "1024"
  roles:
    - wait_for_connection
    - packages
    - firewall
    - security
    - geerlingguy.swap
    - reboot_if_needed
